source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'NNExcelView_Example' do
  pod 'NNExcelView', :path => '../'

   pod 'SnapKit'

  target 'NNExcelView_Tests' do
    inherit! :search_paths

    
  end
end
